### ISSUE TITLE
Error when trying to start with -ssl

### ISSUE THREAD

**Issue by Xurcr0h** [stackp/Droopy#18]
Hey there,

when I try to start Droopy with my letsencrypt cert.pem (I even tried generating a new selfsigned cert for testing purposes), I get the following error:

> Traceback (most recent call last):
>   File "droopy", line 1114, in <module>
>     main()
>   File "droopy", line 1109, in main
>     localisations=default_localisations)
>   File "droopy", line 462, in run
>     server_side=True)
>   File "/usr/lib/python3.5/ssl.py", line 1077, in wrap_socket
>     ciphers=ciphers)
>   File "/usr/lib/python3.5/ssl.py", line 699, in __init__
>     self._context.load_cert_chain(certfile, keyfile)
> ssl.SSLError: [SSL] PEM lib (_ssl.c:2957)

Can you help me, what am I doing wrong?
Thx

**Comment by hdf** [comment]
You need to put the private key in to the certificate PEM file. Normally they are separate, but in this case they are expected to be in the same file.
